### ISSUE TITLE
Error using the example

### ISSUE THREAD

**Issue by EuRoXy** [kavir1698/LifeCalendar.jl#1]
Can't reproduce your example in julia REPL.
```
julia> life_calendar(my_birth_date, expected_years, special_dates)
WARN Missing type for channel "fill", using "nominal" instead.
WARN Missing type for channel "opacity", using "quantitative" instead.
TypeError: Cannot read property 'length' of undefined
    at expression (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_modules/veguild/vega-runtime.js:91:19)
    at Object.operator (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_moduleime/build/vega-runtime.js:111:30)
    at Context.operatorExpression (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/s/vega-runtime/build/vega-runtime.js:647:24)
    at Context.parseOperator (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_a-runtime/build/vega-runtime.js:196:44)
    at /home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/node_ntime.js:29:36
    at Array.forEach (<anonymous>)
    at Context.parse (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_modules/e/build/vega-runtime.js:29:15)
    at runtime (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-v
    at new View (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-
    at render (/home/xinhou/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-cl
```
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```
It also did not work on Win10, with another error.

**Comment by kavir1698** [comment]
I also cannot reproduce your error. The error message shows nothing from this package. Perhaps there is a problem with VegaLite installation. Can you try installing VegaLite again?

**Comment by EuRoXy** [comment]
After adding VegaLite separately, I still got the same error.
Maybe I miss some of the dependencies or the versions aren't compatible.
```
(@v1.5) pkg> status
Status `~/.julia/environments/v1.5/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [336ed68f] CSV v0.7.7
  [a93c6f00] DataFrames v0.21.8
  [dcc97b0b] GeoStats v0.19.0
  [7073ff75] IJulia v1.22.0
  [92561a1c] LifeCalendar v0.2.0 `https://github.com/kavir1698/LifeCalendar.jl.git#main`
  [30363a11] NetCDF v0.10.3
  [e7bfaba1] NumericalIntegration v0.2.0
  [91a5bcdd] Plots v1.7.3
  [c3e4b0f8] Pluto v0.12.15
  [438e738f] PyCall v1.92.1
  [d330b81b] PyPlot v2.9.0
  [1fd47b50] QuadGK v2.4.1
  [f3b207a7] StatsPlots v0.14.17
  [9e3dc215] TimeSeries v0.20.0
  [112f6efa] VegaLite v0.7.0
```

**Comment by kavir1698** [comment]
It is likely because your VegaLite is too old. Yours is v0.7 and mine is v2.3

**Comment by EuRoXy** [comment]
After Pkg updating I only get warnings:
```
julia> life_calendar(my_birth_date, expected_years, special_dates)
WARN Missing type for channel "fill", using "nominal" instead.
WARN Missing type for channel "opacity", using "quantitative" instead.
```
But when I open the pdf file, it is empty. Seems it hasn't been written into.
